### PR TITLE
Move static lastDatabaseUpdate string from home_page to site.json

### PR DESCRIPTION
**Pull request by extrajoss**
So that we can easily change the database update date for future releases I have replaced the date text in the 2 locations in the home_page.ejs file with a site.json config setting.

### CODE REVIEW

**Comment by sacdallago** [comment]
@extrajoss are you still working on the code base here? Cause I've got a huge PR I'm a week away to merge https://github.com/sacdallago/Aquaria :)

**Comment by cstoltenyc** [comment]
That sounds exciting ! By any chance, does that include a non-Java viewer?
Please let me know.
Thanks,
Christian Stolte
________________________________

**Comment by extrajoss** [comment]
Hi Christian,

All done. It was just a quick fix so that I could post new data without
having to update the code to change the date every time. I never went any
deeper than that :)

Looking forward to seeing what you have in store for us.

cheers

J

**Comment by sacdallago** [comment]
@cstoltenyc no :) I haven't gotten around that :)

It's more about packaging of the tool (I dockerized it, also set up an auto deploy), cleaning up build, start  & such scripts, make parameters `ENV`-variable friendly and a few other minor changes... Oh yeah, and then there's the original goal of my project which was to add the possibility to spawn PSSH calculations _on the fly_ by users, which is though of everything done so far the least exciting work.

**Pull request merged**
